version: "3.8"
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
    ports:
      # HTTP Port
      - "80:80"
      # Web UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres-timber:
    container_name: pgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "pgdata_timber:/var/lib/postgresql/data"
    command:
      [
        "postgres",
        "-c",
        "log_statement=mod",
        "-c",
        "log_min_error_statement=ERROR",
      ]
  redis-timber:
    container_name: rdis
    image: "redis:alpine"
    command: >
      --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - "rdbdata_timber:/data"
  timber-api:
    command: modd
    container_name: timber-api
    image: timber-api
    build:
      context: ./api
      target: dev
    volumes:
      - "./api:/app"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      API_URL: ${API_URL}
      AUTH_KEY: ${AUTH_KEY}
      BASE_URL: ${BASE_URL}
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASS: ${REDIS_PASS}
      OAUTH_GOOGLE_ID: ${OAUTH_GOOGLE_ID}
      OAUTH_GOOGLE_SECRET: ${OAUTH_GOOGLE_SECRET}
      OAUTH_GITHUB_ID: ${OAUTH_GITHUB_ID}
      OAUTH_GITHUB_SECRET: ${OAUTH_GITHUB_SECRET}
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timber-api.rule=Host(`localhost`) && PathPrefix(`/api`)"
    volumes:
      - ./api:/go/src/app
    depends_on:
      - postgres-timber
      - redis-timber
      - reverse-proxy
  timber-client:
    container_name: timber-client
    build:
      context: ./ui
      target: dev
    volumes:
      - ./ui:/app
      - /app/node_modules/
    image: timber-client
    command: npm start
    stdin_open: true
    environment:
      BASE_URL: ${BASE_URL}
    expose:
      - "3000"
      - "1234"
    ports:
      - "1234:1234"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.timber-client.rule=Host(`localhost`)"
    volumes:
      - ./ui:/app
      - /app/node_modules
volumes:
  pgdata_timber:
  rdbdata_timber: